/**
 * =============================================================================
 * ITQAN STORE — INVENTORY (inventory.js)
 * =============================================================================
 * MACHINE-GENERATED by admin.html — do not hand-edit unless you must.
 * To add/edit parts, open admin.html in your browser.
 * This file only sets the raw inventory; all logic lives in data.js.
 * =============================================================================
 */
globalThis.ITQAN_INVENTORY = {
  "cpu": [
    {
      "id": "cpu-r5-5600",
      "name": "AMD Ryzen 5 5600",
      "price": 429,
      "socket": "AM4",
      "tdpWatts": 65,
      "integratedGraphics": false,
      "image": "images/cpu.svg",
      "blurb": {
        "ar": "6 أنوية / 12 مسار — أفضل قيمة لفئة الميزانية على منصة AM4",
        "en": "6 cores / 12 threads — best budget value on the AM4 platform"
      }
    },
    {
      "id": "cpu-r5-7600",
      "name": "AMD Ryzen 5 7600",
      "price": 799,
      "socket": "AM5",
      "tdpWatts": 65,
      "integratedGraphics": true,
      "image": "images/cpu.svg",
      "blurb": {
        "ar": "6 أنوية بمعمارية Zen 4 — توازن ممتاز للألعاب بدقة 1080p/1440p",
        "en": "6 Zen 4 cores — a superb balance for 1080p/1440p gaming"
      }
    },
    {
      "id": "cpu-r7-7800x3d",
      "name": "AMD Ryzen 7 7800X3D",
      "price": 1699,
      "socket": "AM5",
      "tdpWatts": 120,
      "integratedGraphics": true,
      "image": "images/cpu.svg",
      "blurb": {
        "ar": "ذاكرة 3D V-Cache — أقوى معالج ألعاب في فئته بلا منازع",
        "en": "3D V-Cache — the undisputed gaming champion of its class"
      }
    },
    {
      "id": "cpu-i5-13400f",
      "name": "Intel Core i5-13400F",
      "price": 649,
      "socket": "LGA1700",
      "tdpWatts": 148,
      "integratedGraphics": false,
      "image": "images/cpu.svg",
      "blurb": {
        "ar": "10 أنوية (6P+4E) — خيار اقتصادي قوي يتطلب كرت شاشة مستقل",
        "en": "10 cores (6P+4E) — a strong budget pick, needs a discrete GPU"
      }
    },
    {
      "id": "cpu-i5-14600k",
      "name": "Intel Core i5-14600K",
      "price": 1099,
      "socket": "LGA1700",
      "tdpWatts": 181,
      "integratedGraphics": true,
      "image": "images/cpu.svg",
      "blurb": {
        "ar": "14 نواة قابلة لكسر السرعة — أداء متعدد المهام ممتاز",
        "en": "14 unlocked cores — excellent multitasking performance"
      }
    },
    {
      "id": "cpu-i7-14700k",
      "name": "Intel Core i7-14700K",
      "price": 1549,
      "socket": "LGA1700",
      "tdpWatts": 253,
      "integratedGraphics": true,
      "image": "images/cpu.svg",
      "blurb": {
        "ar": "20 نواة للإنتاجية الثقيلة والمونتاج — يحتاج تبريدًا قويًا",
        "en": "20 cores for heavy productivity and editing — demands serious cooling"
      }
    }
  ],
  "motherboard": [
    {
      "id": "mb-b550m-ds3h",
      "name": "Gigabyte B550M DS3H",
      "price": 349,
      "socket": "AM4",
      "ramType": "DDR4",
      "formFactor": "mATX",
      "image": "images/motherboard.svg",
      "blurb": {
        "ar": "لوحة AM4 اقتصادية موثوقة بمقاس مدمج",
        "en": "A reliable budget AM4 board in a compact size"
      }
    },
    {
      "id": "mb-b550-tomahawk",
      "name": "MSI MAG B550 Tomahawk",
      "price": 549,
      "socket": "AM4",
      "ramType": "DDR4",
      "formFactor": "ATX",
      "image": "images/motherboard.svg",
      "blurb": {
        "ar": "تغذية كهربائية قوية ومنافذ وفيرة لمنصة AM4",
        "en": "Robust power delivery and generous I/O for AM4"
      }
    },
    {
      "id": "mb-b650m-mortar",
      "name": "MSI MAG B650M Mortar WiFi",
      "price": 699,
      "socket": "AM5",
      "ramType": "DDR5",
      "formFactor": "mATX",
      "image": "images/motherboard.svg",
      "blurb": {
        "ar": "AM5 مدمجة مع WiFi 6E — جاهزة لمعالجات المستقبل",
        "en": "Compact AM5 with WiFi 6E — ready for future CPUs"
      }
    },
    {
      "id": "mb-b650-tuf",
      "name": "ASUS TUF Gaming B650-Plus WiFi",
      "price": 799,
      "socket": "AM5",
      "ramType": "DDR5",
      "formFactor": "ATX",
      "image": "images/motherboard.svg",
      "blurb": {
        "ar": "متانة عسكرية وتبريد VRM ممتاز لفئة AM5 المتوسطة",
        "en": "Military-grade durability and excellent VRM cooling for mid-range AM5"
      }
    },
    {
      "id": "mb-b760m-ddr4",
      "name": "MSI Pro B760M-A DDR4",
      "price": 499,
      "socket": "LGA1700",
      "ramType": "DDR4",
      "formFactor": "mATX",
      "image": "images/motherboard.svg",
      "blurb": {
        "ar": "خيار Intel اقتصادي يستفيد من ذواكر DDR4 الرخيصة",
        "en": "A budget Intel option that leverages cheap DDR4 memory"
      }
    },
    {
      "id": "mb-z790-strix",
      "name": "ASUS ROG Strix Z790-A Gaming WiFi",
      "price": 1299,
      "socket": "LGA1700",
      "ramType": "DDR5",
      "formFactor": "ATX",
      "image": "images/motherboard.svg",
      "blurb": {
        "ar": "فئة عليا لكسر السرعة مع DDR5 ومنافذ Gen5",
        "en": "High-end overclocking board with DDR5 and Gen5 slots"
      }
    }
  ],
  "gpu": [
    {
      "id": "gpu-rx7600",
      "name": "AMD Radeon RX 7600 8GB",
      "price": 999,
      "powerDraw": 165,
      "recommendedPSU": 550,
      "image": "images/gpu.svg",
      "blurb": {
        "ar": "بطل فئة 1080p الاقتصادية بذاكرة 8GB",
        "en": "The budget 1080p champion with 8GB VRAM"
      }
    },
    {
      "id": "gpu-rtx4060",
      "name": "NVIDIA GeForce RTX 4060 8GB",
      "price": 1199,
      "powerDraw": 115,
      "recommendedPSU": 550,
      "image": "images/gpu.svg",
      "blurb": {
        "ar": "كفاءة طاقة استثنائية مع DLSS 3 لدقة 1080p",
        "en": "Exceptional efficiency with DLSS 3 for 1080p"
      }
    },
    {
      "id": "gpu-rtx4060ti",
      "name": "NVIDIA GeForce RTX 4060 Ti 8GB",
      "price": 1599,
      "powerDraw": 165,
      "recommendedPSU": 550,
      "image": "images/gpu.svg",
      "blurb": {
        "ar": "أداء 1080p فائق السلاسة ومدخل مريح لدقة 1440p",
        "en": "Ultra-smooth 1080p and a comfortable entry to 1440p"
      }
    },
    {
      "id": "gpu-rx7800xt",
      "name": "AMD Radeon RX 7800 XT 16GB",
      "price": 2199,
      "powerDraw": 263,
      "recommendedPSU": 700,
      "image": "images/gpu.svg",
      "blurb": {
        "ar": "ذاكرة 16GB — أفضل قيمة مطلقة لفئة 1440p",
        "en": "16GB VRAM — the absolute best value at 1440p"
      }
    },
    {
      "id": "gpu-rtx4070s",
      "name": "NVIDIA GeForce RTX 4070 Super 12GB",
      "price": 2499,
      "powerDraw": 220,
      "recommendedPSU": 650,
      "image": "images/gpu.svg",
      "blurb": {
        "ar": "أداء 1440p ممتاز مع تتبع أشعة قوي وDLSS 3.5",
        "en": "Excellent 1440p with strong ray tracing and DLSS 3.5"
      }
    },
    {
      "id": "gpu-rtx4080s",
      "name": "NVIDIA GeForce RTX 4080 Super 16GB",
      "price": 4299,
      "powerDraw": 320,
      "recommendedPSU": 750,
      "image": "images/gpu.svg",
      "blurb": {
        "ar": "وحش دقة 4K — لعب سلس بأقصى الإعدادات",
        "en": "A 4K monster — fluid gaming at maximum settings"
      }
    }
  ],
  "ram": [
    {
      "id": "ram-lpx-16-d4",
      "name": "Corsair Vengeance LPX 16GB (2×8) DDR4-3200",
      "price": 189,
      "type": "DDR4",
      "capacity": "16GB",
      "speed": "DDR4-3200",
      "image": "images/ram.svg",
      "blurb": {
        "ar": "الخيار الكلاسيكي الموثوق لمنصات DDR4",
        "en": "The classic, trusted pick for DDR4 platforms"
      }
    },
    {
      "id": "ram-fury-32-d4",
      "name": "Kingston Fury Beast 32GB (2×16) DDR4-3600",
      "price": 329,
      "type": "DDR4",
      "capacity": "32GB",
      "speed": "DDR4-3600",
      "image": "images/ram.svg",
      "blurb": {
        "ar": "سعة مريحة وسرعة مثالية لمعالجات Ryzen 5000",
        "en": "Comfortable capacity at the sweet-spot speed for Ryzen 5000"
      }
    },
    {
      "id": "ram-fury-16-d5",
      "name": "Kingston Fury Beast 16GB (2×8) DDR5-5200",
      "price": 279,
      "type": "DDR5",
      "capacity": "16GB",
      "speed": "DDR5-5200",
      "image": "images/ram.svg",
      "blurb": {
        "ar": "مدخل اقتصادي لعالم DDR5",
        "en": "An affordable entry into DDR5"
      }
    },
    {
      "id": "ram-veng-32-d5",
      "name": "Corsair Vengeance 32GB (2×16) DDR5-6000",
      "price": 449,
      "type": "DDR5",
      "capacity": "32GB",
      "speed": "DDR5-6000",
      "image": "images/ram.svg",
      "blurb": {
        "ar": "السرعة المثالية 6000MT/s لمعالجات Ryzen 7000",
        "en": "The ideal 6000MT/s speed for Ryzen 7000 CPUs"
      }
    },
    {
      "id": "ram-z5-32-d5",
      "name": "G.Skill Trident Z5 RGB 32GB (2×16) DDR5-6400",
      "price": 599,
      "type": "DDR5",
      "capacity": "32GB",
      "speed": "DDR5-6400",
      "image": "images/ram.svg",
      "blurb": {
        "ar": "أداء نخبوي مع إضاءة RGB راقية",
        "en": "Elite performance with tasteful RGB lighting"
      }
    }
  ],
  "storage": [
    {
      "id": "st-nv2-500",
      "name": "Kingston NV2 500GB NVMe Gen4",
      "price": 149,
      "capacity": "500GB",
      "type": "NVMe",
      "image": "images/storage.svg",
      "blurb": {
        "ar": "قرص نظام سريع بسعر اقتصادي",
        "en": "A fast boot drive at a budget price"
      }
    },
    {
      "id": "st-980-1tb",
      "name": "Samsung 980 1TB NVMe",
      "price": 279,
      "capacity": "1TB",
      "type": "NVMe",
      "image": "images/storage.svg",
      "blurb": {
        "ar": "موثوقية سامسونج بسرعات تصل 3500MB/s",
        "en": "Samsung reliability at up to 3,500MB/s"
      }
    },
    {
      "id": "st-sn850x-1tb",
      "name": "WD Black SN850X 1TB NVMe Gen4",
      "price": 399,
      "capacity": "1TB",
      "type": "NVMe",
      "image": "images/storage.svg",
      "blurb": {
        "ar": "من أسرع أقراص الألعاب — 7300MB/s",
        "en": "One of the fastest gaming drives — 7,300MB/s"
      }
    },
    {
      "id": "st-870evo-1tb",
      "name": "Samsung 870 EVO 1TB SATA",
      "price": 329,
      "capacity": "1TB",
      "type": "SATA",
      "image": "images/storage.svg",
      "blurb": {
        "ar": "قرص SATA ممتاز كتخزين إضافي للملفات والألعاب",
        "en": "A superb SATA drive for extra game and file storage"
      }
    }
  ],
  "psu": [
    {
      "id": "psu-mwe-550",
      "name": "Cooler Master MWE 550W",
      "price": 199,
      "wattage": 550,
      "rating": "Bronze",
      "image": "images/psu.svg",
      "blurb": {
        "ar": "مزود موثوق للتجميعات الاقتصادية",
        "en": "A dependable unit for budget builds"
      }
    },
    {
      "id": "psu-cx650",
      "name": "Corsair CX650 650W",
      "price": 259,
      "wattage": 650,
      "rating": "Bronze",
      "image": "images/psu.svg",
      "blurb": {
        "ar": "خيار متوازن يغطي الفئة المتوسطة بأمان",
        "en": "A balanced choice that covers mid-range safely"
      }
    },
    {
      "id": "psu-rm750e",
      "name": "Corsair RM750e 750W",
      "price": 399,
      "wattage": 750,
      "rating": "Gold",
      "image": "images/psu.svg",
      "blurb": {
        "ar": "كفاءة Gold وكابلات قابلة للفصل بالكامل",
        "en": "Gold efficiency with fully modular cabling"
      }
    },
    {
      "id": "psu-gx850",
      "name": "Seasonic Focus GX-850 850W",
      "price": 549,
      "wattage": 850,
      "rating": "Gold",
      "image": "images/psu.svg",
      "blurb": {
        "ar": "جودة Seasonic الأسطورية مع ضمان 10 سنوات",
        "en": "Legendary Seasonic quality with a 10-year warranty"
      }
    },
    {
      "id": "psu-rm1000e",
      "name": "Corsair RM1000e 1000W",
      "price": 699,
      "wattage": 1000,
      "rating": "Gold",
      "image": "images/psu.svg",
      "blurb": {
        "ar": "هامش وفير لأقوى الكروت وترقيات المستقبل",
        "en": "Ample headroom for flagship GPUs and future upgrades"
      }
    }
  ],
  "case": [
    {
      "id": "case-q300l",
      "name": "Cooler Master MasterBox Q300L",
      "price": 199,
      "formFactorSupport": [
        "mATX",
        "Mini-ITX"
      ],
      "image": "images/case.svg",
      "blurb": {
        "ar": "صندوق مدمج عملي للوحات mATX",
        "en": "A practical compact case for mATX boards"
      }
    },
    {
      "id": "case-h5-flow",
      "name": "NZXT H5 Flow",
      "price": 349,
      "formFactorSupport": [
        "ATX",
        "mATX",
        "Mini-ITX"
      ],
      "image": "images/case.svg",
      "blurb": {
        "ar": "تدفق هواء ممتاز وتصميم نظيف أنيق",
        "en": "Excellent airflow in a clean, elegant design"
      }
    },
    {
      "id": "case-lancool216",
      "name": "Lian Li Lancool 216",
      "price": 399,
      "formFactorSupport": [
        "ATX",
        "mATX",
        "Mini-ITX"
      ],
      "image": "images/case.svg",
      "blurb": {
        "ar": "مروحتان أماميتان 160mm — ملك التبريد الهوائي",
        "en": "Dual 160mm front fans — the air-cooling king"
      }
    },
    {
      "id": "case-y60",
      "name": "HYTE Y60",
      "price": 749,
      "formFactorSupport": [
        "ATX",
        "mATX",
        "Mini-ITX"
      ],
      "image": "images/case.svg",
      "blurb": {
        "ar": "زجاج بانورامي ثلاثي — قطعة فنية لعرض تجميعتك",
        "en": "Panoramic triple glass — a showcase piece for your build"
      }
    }
  ],
  "cooler": [
    {
      "id": "cool-ak400",
      "name": "DeepCool AK400",
      "price": 129,
      "tdpSupport": 220,
      "image": "images/cooler.svg",
      "blurb": {
        "ar": "مبرد هوائي اقتصادي بأداء يفوق سعره",
        "en": "A budget air cooler that punches above its price"
      }
    },
    {
      "id": "cool-pa120se",
      "name": "Thermalright Peerless Assassin 120 SE",
      "price": 169,
      "tdpSupport": 245,
      "image": "images/cooler.svg",
      "blurb": {
        "ar": "برجان وست أنابيب حرارية — أفضل قيمة تبريد هوائي",
        "en": "Twin towers, six heat pipes — the best air-cooling value"
      }
    },
    {
      "id": "cool-lt520",
      "name": "DeepCool LT520 240mm AIO",
      "price": 399,
      "tdpSupport": 250,
      "image": "images/cooler.svg",
      "blurb": {
        "ar": "تبريد مائي 240mm بمضخة قوية وإضاءة أنيقة",
        "en": "240mm liquid cooling with a strong pump and subtle lighting"
      }
    },
    {
      "id": "cool-kraken360",
      "name": "NZXT Kraken 360mm AIO",
      "price": 699,
      "tdpSupport": 350,
      "image": "images/cooler.svg",
      "blurb": {
        "ar": "تبريد مائي 360mm بشاشة LCD — للمعالجات الأشرس",
        "en": "360mm liquid cooling with an LCD — for the fiercest CPUs"
      }
    }
  ]
};
