/**
 * =============================================================================
 * ITQAN STORE — STORE SETTINGS (settings.js)
 * =============================================================================
 * MACHINE-GENERATED by admin.html (قسم «إعدادات المتجر») — يمكن تعديله يدويًا.
 *
 * whatsappPhone : رقم واتساب المتجر بصيغة دولية بدون + (مثال: 966512345678)
 * ai            : إعداد مساعد الذكاء الاصطناعي المشترك لكل الزوار
 *                 { provider: 'gemini'|'openai'|'anthropic', model, apiKey }
 * admin         : بيانات دخول لوحة التحكم (الافتراضي 123 / 123 — غيّرها من داخل اللوحة)
 *                 passHash = SHA-256 لكلمة المرور (لا تُخزَّن كنص صريح)
 *
 * ⚠️ تحذير أمني: هذا الملف يُرسَل لكل زائر، فأي مفتاح/بيانات هنا مرئية للعامة.
 * =============================================================================
 */
globalThis.ITQAN_SETTINGS = {
  "whatsappPhone": "966542585400",
  "ai": {
    "provider": "anthropic",
    "model": "claude-haiku-4-5",
    "proxyUrl": "https://itcanstore.nosososo68.workers.dev/",
    "apiKey": ""
  },
  "social": [],
  "admin": {
    "mode": "user",
    "user": "123",
    "passHash": "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3"
  }
};
